#cloud-config
ssh_authorized_keys:
- ssh-rsa <...>
runcmd:
#install docker-ce
- apt-get update
- apt-get install -y apt-transport-https ca-certificates curl software-properties-common
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- apt-get update
- apt-get -y install docker-ce=5:18.09.0~3-0~ubuntu-bionic
- usermod -G docker -a azureuser