# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  SWEAGLE_MAPPED_TENANT: $(SWEAGLE_TENANT)
  CDS: 'azure-devops'

trigger:
- master

resources:
  containers:
#  - container: new-cli
#    endpoint: sweagle_docker_registry
#    image: 'sweagle-docker/sweagle-azure-cli:1.1.0-azp3.8.0'
  - container: sweagle-cli
    image: 'dsweagle/sweagle-azure-cli:1.1.0-azp3.8.0'
  - container: new-cli
    endpoint: sweagle_docker_registry
    image: 'sweagle-docker/sweagle-azure-cli:1.1.0-azp3.8.0'
  - container: u16
    image: ubuntu:16.04

stages:

- stage: Test
  jobs:
  - job: Test_vm
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzurePowerShell@4
      displayName: 'List AzurePwsh4 Modules'
      inputs:
        azureSubscription: 'PayPerUse(3269938e-a582-4880-95da-7ef80a7162a3)'
        ScriptType: 'InlineScript'
        Inline: 'Get-Module -ListAvailable'
        azurePowerShellVersion: 'LatestVersion'

  - job: Test_cli
    container: 'new-cli'
    steps:
    - script: |
        curl -skX POST $SWEAGLE_MAPPED_TENANT/api/v1/tenant/metadata-parser/parse -H "Authorization: bearer $SWEAGLE_MAPPED_TOKEN" --data-binary "mds=$CDS&parser=returnDataforNode&args=vm&format=JSON&arraySupport=true" | jq .
      displayName: 'Test curl export command'
    # secret variables must be defined as env variable directly in step where it is used
      env:
        SWEAGLE_MAPPED_TOKEN: $(SWEAGLE_TOKEN)

    - task: PowerShell@2
      displayName: 'Test Powershell2 with Inline Script'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'
    - task: AzurePowerShell@4
      displayName: 'Test AzurePwsh4 with Inline Script'
      inputs:
        azureSubscription: 'PayPerUse(3269938e-a582-4880-95da-7ef80a7162a3)'
        ScriptType: 'InlineScript'
        Inline: 'Get-Module -ListAvailable'
        azurePowerShellVersion: 'LatestVersion'
#        azurePowerShellVersion: '3.8.0'
#        preferredAzurePowerShellVersion: '3.8.0'
    - task: AzurePowerShell@4
      displayName: 'Test Pwsh4 with Filepath Script'
      inputs:
        azureSubscription: 'PayPerUse(3269938e-a582-4880-95da-7ef80a7162a3)'
        ScriptType: 'FilePath'
        ScriptPath: 'arm/parse-input.ps1'
        azurePowerShellVersion: LatestVersion
#        preferredAzurePowerShellVersion: '3.5.0'
#        pwsh: true

- stage: Validate_Config
  jobs:
  - job: Sweagle_Steps_with_cli
    container: 'sweagle-cli'
    # this is if you want to target directly the azure-cli available on docker hub instead of SWEAGLE registry
    #container:
    #  image: 'dsweagle/sweagle-azure-cli:1.0.0'

    steps:
    # you should always configure the CLI before use because temporary folders are created at each pipeline run and db.json must be located there
    - script: curl https://testing.sweagle.com/info
      displayName: 'Test connection to SWEAGLE Tenant'

    # you should always configure the CLI before use because temporary folders are created at each pipeline run and db.json must be located there
    - script: |
        sweagle options --newenv $SWEAGLE_MAPPED_TENANT --newusername azurePipeline --newtoken $SWEAGLE_MAPPED_TOKEN
        sweagle info
      displayName: 'Configure and test SWEAGLE CLI'
    # secret variables must be defined as env variable directly in step where it is used
      env:
        SWEAGLE_MAPPED_TOKEN: $(SWEAGLE_TOKEN)

    - script: |
        URL=$(sweagle export $(CDS) --exporter returnValueforKey --argsList $URL_TO_GET --format PROPS)
        FORMAT=$(echo "${URL##*.}")
        FILENAME="${URL##*/}"
        echo "##vso[task.setvariable variable=URL]$URL"
        echo "##vso[task.setvariable variable=FORMAT]$FORMAT"
        echo "##vso[task.setvariable variable=FILENAME]$FILENAME"
        echo "URL= $URL"
        echo "FILENAME= $FILENAME"
        echo "FORMAT= $FORMAT"
      displayName: 'Call SWEAGLE to get URL'

    - script: |
        curl $(URL) --output ./result.$(FORMAT)
        cat ./result.$FORMAT
      displayName: 'Call URL to get file'

    - script: |
        echo "cpu=$CPU" >> ./result.$(FORMAT)
        echo "ram=$RAM" >> ./result.$(FORMAT)
      displayName: 'Fill template with pipeline variables'

    - script: |
        NODENAME=$(cat ./result.$(FORMAT) | grep "^name=" | cut -d'=' -f2)
        echo "##vso[task.setvariable variable=NODENAME]$NODENAME"
        sweagle uploadData --filePath ./result.$(FORMAT) --nodePath azure-devops,outputs,$NODENAME --type $(FORMAT) --autoRecognize --autoApprove
      displayName: 'Upload data to SWEAGLE'

    #- script: |
    #    response=$(sweagle validate --validator noEmptyValues --forIncoming --pretty $(CDS))
    #    if [[ $response == *"Request failed with status code 404"* ]]; then
    #      echo "### No pending DCS, trying with stored values instead ###"
    #      response=$(sweagle validate --validator noEmptyValues --pretty $(CDS))
    #    fi
    #    echo $response
    #    if [[ ${response,,} == *"error"* ]]; then exit 1; fi
    #  displayName: 'Validate Changes'

    # Call SWEAGLE CLI redirecting both stderr and stdout to same variable
    # This is because CLI redirects errors to stderr
    - script: |
        response=$(sweagle validationStatus --withData --forIncoming --pretty $CDS 2>&1)
        if [[ $response == *"Request failed with status code 404"* ]]; then
          echo "### No pending CDS, trying with stored values instead ###"
          response=$(sweagle validationStatus --withData --pretty $CDS 2>&1)
        fi
        echo "$response"
        if [[ ${response,,} == *"error"* ]]; then echo "FAIL TASK"; exit 1; fi
      displayName: 'Get validation status for CDS'

    - script: |
        mkdir -p $(Pipeline.Workspace)/artifacts
        sweagle storeSnapshots --configdatasetName $(CDS) --snapshotTag $(Build.BuildNumber) --level error
        sweagle export $(CDS) --exporter returnDataforNode --format $(FORMAT) --argsList $(NODENAME) > ./output.$(FORMAT)
        sweagle export $(CDS) --exporter returnDataforNode --format json --argsList 'vm-params' > $(Pipeline.Workspace)/artifacts/vm-params.json
        echo "###################################"
        echo "#####   DISPLAY OUTPUT FILE   #####"
        echo "###################################"
        echo "FILENAME = $(FILENAME)"
        if [ "${FORMAT,,}" = "json" ]; then
          cat ./output.$(FORMAT) | jq .
        else
          cat ./output.$(FORMAT)
        fi
        echo "FILENAME = VM-PARAMS.json"
        cat $(Pipeline.Workspace)/artifacts/vm-params.json
      displayName: 'Snapshot and get configuration'

    # Publish the folder as pipeline artifact
    - publish: $(Pipeline.Workspace)/artifacts
      artifact: artifacts
      displayName: 'Publish Artifacts'


- stage: Deploy_VM
  jobs:
  - job: Powershell_Steps
    pool:
      vmImage: 'ubuntu-latest'
#    container: 'u16'

    steps:

    # Download the artifacts
    - download: current
      artifact: artifacts
      displayName: 'Download Artifacts'

    - script: cat $(Pipeline.Workspace)/artifacts/vm-params.json
      displayName: 'Display artifact'

    - script: |
        echo "URL= $URL"
        echo "FILENAME= $FILENAME"
        echo "FORMAT= $FORMAT"
        cat ./output.json | jq .

    - task: PowerShell@2
      inputs:
        filePath: 'arm/parse-input.ps1'

    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'PayPerUse(3269938e-a582-4880-95da-7ef80a7162a3)'
        ScriptType: 'FilePath'
        ScriptPath: 'arm/parse-input.ps1'
        azurePowerShellVersion: '3.5.0'
    #    azurePowerShellVersion: LatestVersion
        preferredAzurePowerShellVersion: '3.5.0'


#    - task: AzureResourceManagerTemplateDeployment@3
#      inputs:
#        deploymentScope: 'Resource Group'
#        azureResourceManagerConnection: 'PayPerUse(3269938e-a582-4880-95da-7ef80a7162a3)'
#        subscriptionId: '3269938e-a582-4880-95da-7ef80a7162a3'
#        action: Create Or Update Resource Group
#        resourceGroupName: test-sweagle
#        location: 'France Central'
#        templateLocation: 'Linked artifact'
#        csmFile: 'arm/template.json'
#        csmParametersFile: 'arm/parameters.json'
#        deploymentMode: 'Incremental'
#        deploymentOutputs: outputArm
