version: 2.1

orbs:
  # Replace this with your own!
  swgl-orb: cyr-riv/swgl-orb@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  docker: circleci/docker@2.0.2

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent that the orb is valid.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  test-swgl-registry:
    machine: true
    steps:
      - checkout
      - run:
          name: 'pre-checks step'
          command: |
            echo 'SWGLREGISTRY_USERNAME'
            echo 'SWGLREGISTRY_PASSWORD'
      - docker/check:
          docker-username: SWGLREGISTRY_USERNAME
          docker-password: SWGLREGISTRY_PASSWORD
          registry: 'docker.sweagle.com:8444'
      - docker/pull:
          images: 'docker.sweagle.com:8444/sweagle-docker/sweagle-cli:1.1.4'

workflows:
  version: 2
  test-orb:
    unless: <<pipeline.parameters.run-integration-tests>>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      #- shellcheck/check:
      #    dir: ./src/scripts
      #    exclude: SC2148
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: cyr-riv/swgl-orb
          requires:
            - orb-tools/lint
            - orb-tools/pack
      #      - shellcheck/check
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: cyr-riv/swgl-orb
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          filters:
            branches:
              only:
                - master
                - main
  sweagle:
    when: <<pipeline.parameters.run-integration-tests>>
    jobs:
      #- test-swgl-registry
      - swgl-orb/uploading-data
      - swgl-orb/cds-is-valid:
          requires:
          - swgl-orb/uploading-data
      - swgl-orb/cds-is-stored:
          requires:
          - swgl-orb/cds-is-valid
      - swgl-orb/exporting-data:
          requires:
          - swgl-orb/cds-is-stored
