---
## Prerequisites:
## Packages Ansible 2.5 or higher + package sshpass
## be sure ansible.cfg knows your inventory folder and authorize non ssh checks
# more /etc/ansible/ansible.cfg

## WARNING
## Test connection to targeted hosts with
# ansible all -i ./inventories/test/hosts.yml -m ping

## Test with
# ansible-playbook info.yml -i ./inventories/hosts.yml --check

## For full SWEAGLE cycle (upload, validate, snapshot, export)
# ansible-playbook all.yml -i ./inventories/hosts.yml

- hosts: all
  roles:
    - sweagle/info
