---

- name: ALL - Get list of files to upload
  find:
    paths: "{{ paths }}"
#    patterns: "*.properties,*.json"
    patterns: "{{ patterns }}"
    recurse: "{{ recurse }}"
    excludes: "{{ excludes }}"
  register: find_result

- name: ALL - Initialise
  set_fact:
    upload_data_list: []

- name: Build  for linux
  set_fact:
    upload_data_list: "{{ upload_data_list }} + [{ 'file_path': \"{{ item.path }}\",\
      'node_path': \"{{ item.path | replace('/',',') | regex_replace('^,','') }}\",\
      'format': \"{{ item.path | splitext | last | replace('.','') }}\" }]"
  loop: "{{ find_result.files }}"
  loop_control:
    label: "Add file {{ item.path }}"
  when: ansible_os_family != "Windows"

- name: Build upload_data_list for windows
  set_fact:
    upload_data_list: "{{ upload_data_list }} + [{ 'file_path': \"{{ item.path }}\",\
      'node_path': \"{{ item.path | win_splitdrive | last | replace('\\',',') | regex_replace('^,','') }}\",\
      'format': \"{{ item.path | splitext | last | replace('.','') }}\" }]"
  loop: "{{ find_result.files }}"
  loop_control:
    label: "Add file {{ item.path }}"
  when: ansible_os_family == "Windows"

#- name: "Display file list"
#  debug:
#    var: upload_data_list

- name: ALL - Call uploadFile role
  include_role:
    name: sweagle/uploadFile
